/* AUTO-GENERATED by scripts/generate-tokens.mjs — DO NOT EDIT.
   Source: src/styles/tokens/primitives.ts (surface). Run `pnpm generate:tokens`. */

export const THEME_COLOR = {
  light: "#f6f1e9",
  dark: "#121920",
} as const;
