/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Логин и пароль */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["auth.loginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать лекцию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные лекции */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["lecture.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["lecture.Lecture"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить лекцию */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Данные для обновления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["lecture.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["lecture.Lecture"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить лекцию */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать/обновить транскрипт */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Сегменты транскрипта */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["transcript.upsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Тип файла (videos|notes|transcripts) */
                        type: string;
                        /** @description ID лекции */
                        lecture_id: string;
                        /**
                         * Format: binary
                         * @description Файл
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список лекций */
        get: {
            parameters: {
                query?: {
                    /** @description Номер страницы */
                    page?: number;
                    /** @description Записей на странице */
                    limit?: number;
                    /** @description Поиск по названию/описанию */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["lecture.ListResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить лекцию */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["lecture.Lecture"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить транскрипт лекции */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["transcript.Transcript"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "auth.loginRequest": {
            password?: string;
            username?: string;
        };
        "lecture.CreateRequest": {
            date?: string;
            description?: string;
            title?: string;
        };
        "lecture.Lecture": {
            created_at?: string;
            date?: string;
            description?: string;
            id?: string;
            notes_url?: string;
            title?: string;
            updated_at?: string;
            video_url?: string;
        };
        "lecture.ListResult": {
            data?: components["schemas"]["lecture.Lecture"][];
            pagination?: components["schemas"]["lecture.PaginationMeta"];
        };
        "lecture.PaginationMeta": {
            limit?: number;
            page?: number;
            total?: number;
        };
        "lecture.UpdateRequest": {
            date?: string;
            description?: string;
            title?: string;
        };
        "transcript.Segment": {
            end?: number;
            id?: number;
            speaker?: string;
            start?: number;
            text?: string;
        };
        "transcript.Transcript": {
            created_at?: string;
            id?: string;
            lecture_id?: string;
            segments?: components["schemas"]["transcript.Segment"][];
            updated_at?: string;
        };
        "transcript.upsertRequest": {
            segments?: components["schemas"]["transcript.Segment"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
