/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пометку (админ) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/annotations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус пометки (админ) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["github_com_Mrartman14_philosophy-api_internal_moderation.UpdateStatusRequest"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить комментарий (админ) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус комментария (админ) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["github_com_Mrartman14_philosophy-api_internal_moderation.UpdateStatusRequest"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать лекцию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные лекции */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_lecture.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_lecture.Lecture"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить лекцию */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Данные для обновления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_lecture.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_lecture.Lecture"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить лекцию */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл лекции */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Тип файла (video|notes|image) */
                        type: string;
                        /**
                         * Format: binary
                         * @description Файл
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_lecturefile.LectureFile"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить файл лекции */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID файла */
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать/обновить транскрипт (полная замена) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Сегменты транскрипта */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_transcript.upsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить сегмент */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Данные сегмента */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_transcript.CreateSegmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_transcript.Segment"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript/segments/{segmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить сегмент */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID сегмента */
                    segmentId: string;
                };
                cookie?: never;
            };
            /** @description Поля для обновления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_transcript.UpdateSegmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_transcript.Segment"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить сегмент */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID сегмента */
                    segmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/push/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить push-уведомление */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные уведомления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_push.SendRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /**
                         * @description Тип файла
                         * @enum {string}
                         */
                        type: "videos" | "notes" | "transcripts";
                        /** @description ID лекции */
                        lecture_id: string;
                        /**
                         * Format: binary
                         * @description Файл
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: {
                                key?: string;
                                url?: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус пользователя (модератор+) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Новый статус */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_user.UpdateStatusRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пометку по ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_annotation.Annotation"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Редактировать пометку */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Обновлённые данные */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_annotation.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_annotation.Annotation"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить свою пометку */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["internal_user.RegisterRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: {
                                token?: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["internal_user.RegisterRequest"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_user.User"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Редактировать комментарий */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Новый текст */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_comment.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_comment.Comment"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить свой комментарий */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Поставить реакцию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Реакция */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_comment.AddReactionRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Убрать реакцию */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список лекций */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                    /** @description Поиск по названию/описанию */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ListResponse"] & {
                            data?: components["schemas"]["internal_lecture.Lecture"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить лекцию */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_lecture.Lecture"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пометок к лекции */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                    /** @description Фильтр по сегменту */
                    segment_id?: number;
                };
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ListResponse"] & {
                            data?: components["schemas"]["internal_annotation.Annotation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Создать пометку */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Пометка */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_annotation.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_annotation.Annotation"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список комментариев к лекции */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ListResponse"] & {
                            data?: components["schemas"]["internal_comment.Comment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Создать комментарий */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Комментарий */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_comment.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_comment.Comment"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список файлов лекции */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_lecturefile.LectureFile"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить транскрипт лекции */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: components["schemas"]["internal_transcript.Transcript"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подписаться на push-уведомления */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные подписки */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_push.SubscribeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Отписаться от push-уведомлений */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Endpoint подписки */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_push.UnsubscribeRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/vapid-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить VAPID public key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Response"] & {
                            data?: {
                                publicKey?: string;
                            };
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Глобальный поиск */
        get: {
            parameters: {
                query: {
                    /** @description Поисковый запрос */
                    q: string;
                    /** @description Лимит результатов */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ListResponse"] & {
                            data?: components["schemas"]["internal_search.LectureHit"][];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_Mrartman14_philosophy-api_internal_httputil.ErrorResponse": {
            code?: string;
            error?: string;
        };
        "github_com_Mrartman14_philosophy-api_internal_httputil.ListResponse": {
            data?: unknown;
            pagination?: components["schemas"]["github_com_Mrartman14_philosophy-api_internal_httputil.Pagination"];
        };
        "github_com_Mrartman14_philosophy-api_internal_httputil.Pagination": {
            limit?: number;
            offset?: number;
            total?: number;
        };
        "github_com_Mrartman14_philosophy-api_internal_httputil.Response": {
            data?: unknown;
        };
        "github_com_Mrartman14_philosophy-api_internal_httputil.ValidationErrorResponse": {
            code?: string;
            error?: string;
            fields?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        "github_com_Mrartman14_philosophy-api_internal_moderation.ModerationStatus": "published" | "hidden" | "pending";
        "github_com_Mrartman14_philosophy-api_internal_moderation.UpdateStatusRequest": {
            /** @enum {unknown} */
            status: "published" | "hidden" | "pending";
        };
        /** @enum {string} */
        "github_com_Mrartman14_philosophy-api_internal_rbac.Role": "user" | "moderator" | "admin";
        /** @enum {string} */
        "github_com_Mrartman14_philosophy-api_internal_rbac.Status": "active" | "suspended" | "banned";
        "internal_annotation.Annotation": {
            author?: components["schemas"]["internal_annotation.Author"];
            body: string;
            comment_count?: number;
            created_at: string;
            id: string;
            is_anonymous?: boolean;
            is_edited?: boolean;
            is_private?: boolean;
            lecture_id: string;
            /** @description Populated by service */
            segment_ids?: number[];
            status: components["schemas"]["github_com_Mrartman14_philosophy-api_internal_moderation.ModerationStatus"];
            updated_at: string;
        };
        "internal_annotation.Author": {
            username?: string;
        };
        "internal_annotation.CreateRequest": {
            body: string;
            is_anonymous?: boolean;
            is_private?: boolean;
            lecture_id?: string;
            segment_ids: number[];
        };
        "internal_annotation.UpdateRequest": {
            body: string;
            segment_ids: number[];
        };
        "internal_comment.AddReactionRequest": {
            /** @enum {unknown} */
            reaction: "like";
        };
        "internal_comment.Author": {
            username?: string;
        };
        "internal_comment.Comment": {
            annotation_id?: string;
            /** @description Populated by service */
            author?: components["schemas"]["internal_comment.Author"];
            body: string;
            created_at: string;
            id: string;
            is_anonymous?: boolean;
            is_edited?: boolean;
            lecture_id: string;
            my_reaction?: components["schemas"]["internal_comment.ReactionType"];
            parent_id?: string;
            reactions?: components["schemas"]["internal_comment.ReactionSummary"];
            replies?: components["schemas"]["internal_comment.Comment"][];
            status: components["schemas"]["github_com_Mrartman14_philosophy-api_internal_moderation.ModerationStatus"];
            updated_at: string;
        };
        "internal_comment.CreateRequest": {
            annotation_id?: string;
            body: string;
            is_anonymous?: boolean;
            lecture_id?: string;
            parent_id?: string;
        };
        "internal_comment.ReactionSummary": {
            like?: number;
        };
        /** @enum {string} */
        "internal_comment.ReactionType": "like";
        "internal_comment.UpdateRequest": {
            body: string;
        };
        "internal_lecture.CreateRequest": {
            date: string;
            description?: string;
            title: string;
        };
        "internal_lecture.Lecture": {
            created_at: string;
            date: string;
            description: string;
            id: string;
            title: string;
            updated_at: string;
        };
        "internal_lecture.UpdateRequest": {
            date?: string;
            description?: string;
            title?: string;
        };
        /** @enum {string} */
        "internal_lecturefile.FileType": "video" | "notes" | "image";
        "internal_lecturefile.LectureFile": {
            created_at: string;
            filename: string;
            id: string;
            lecture_id: string;
            sort_order?: number;
            type: components["schemas"]["internal_lecturefile.FileType"];
            url?: string;
        };
        "internal_push.SendRequest": {
            body?: string;
            title: string;
            url?: string;
        };
        "internal_push.SubscribeKeys": {
            auth: string;
            p256dh: string;
        };
        "internal_push.SubscribeRequest": {
            endpoint: string;
            keys: components["schemas"]["internal_push.SubscribeKeys"];
        };
        "internal_push.UnsubscribeRequest": {
            endpoint: string;
        };
        "internal_search.LectureHit": {
            date: string;
            lecture_id: string;
            matches?: components["schemas"]["internal_search.Match"][];
            title: string;
        };
        "internal_search.Match": {
            segment_id?: string;
            source: string;
            text: string;
        };
        "internal_transcript.CreateSegmentRequest": {
            end?: number;
            position?: number;
            speaker: string;
            start?: number;
            text: string;
        };
        "internal_transcript.Segment": {
            end?: number;
            id: string;
            position?: number;
            speaker: string;
            start?: number;
            text: string;
        };
        "internal_transcript.Transcript": {
            created_at: string;
            id: string;
            lecture_id: string;
            segments?: components["schemas"]["internal_transcript.Segment"][];
            updated_at: string;
        };
        "internal_transcript.UpdateSegmentRequest": {
            end?: number;
            position?: number;
            speaker?: string;
            start?: number;
            text?: string;
        };
        "internal_transcript.upsertRequest": {
            segments?: components["schemas"]["internal_transcript.Segment"][];
        };
        "internal_user.RegisterRequest": {
            password: string;
            username: string;
        };
        "internal_user.UpdateStatusRequest": {
            /** @enum {unknown} */
            status: "active" | "suspended" | "banned";
        };
        "internal_user.User": {
            created_at: string;
            id: string;
            role: components["schemas"]["github_com_Mrartman14_philosophy-api_internal_rbac.Role"];
            status: components["schemas"]["github_com_Mrartman14_philosophy-api_internal_rbac.Status"];
            updated_at: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Username и пароль */
        "internal_user.RegisterRequest": {
            content: {
                "application/json": components["schemas"]["internal_user.RegisterRequest"];
            };
        };
        /** @description Новый статус */
        "github_com_Mrartman14_philosophy-api_internal_moderation.UpdateStatusRequest": {
            content: {
                "application/json": components["schemas"]["github_com_Mrartman14_philosophy-api_internal_moderation.UpdateStatusRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
