/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пометок лекции (админ, без фильтра по статусу) */
        get: {
            parameters: {
                query: {
                    /** @description ID лекции */
                    lecture_id: string;
                    /** @description Фильтр статусов через запятую: published,hidden,pending */
                    status?: string;
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["annotation.Annotation"][];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пометку (админ) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/annotations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус пометки (админ) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["moderation.UpdateStatusRequest"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список записей admin audit log */
        get: {
            parameters: {
                query?: {
                    /** @description ID актора */
                    actor?: string;
                    /** @description Тип цели */
                    target_type?: string;
                    /** @description ID цели */
                    target_id?: string;
                    /** @description Действие */
                    action?: string;
                    /** @description RFC3339 */
                    from?: string;
                    /** @description RFC3339 */
                    to?: string;
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["audit.Record"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список комментариев лекции (админ, без фильтра по статусу) */
        get: {
            parameters: {
                query: {
                    /** @description ID лекции */
                    lecture_id: string;
                    /** @description Фильтр статусов через запятую: published,hidden,pending */
                    status?: string;
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["comment.Comment"][];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить комментарий (админ) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус комментария (админ) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["moderation.UpdateStatusRequest"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать лекцию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные лекции */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["lecture.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["lecture.Lecture"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить лекцию */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Данные для обновления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["lecture.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["lecture.Lecture"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить лекцию */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить файл лекции */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Тип файла (video|notes|image) */
                        type: string;
                        /**
                         * Format: binary
                         * @description Файл
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["lecturefile.LectureFile"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить файл лекции */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID файла */
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать/обновить транскрипт (полная замена) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Сегменты транскрипта */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["transcript.upsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить сегмент */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Данные сегмента */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["transcript.CreateSegmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["transcript.Segment"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lectures/{id}/transcript/segments/{segmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Обновить сегмент */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID сегмента */
                    segmentId: string;
                };
                cookie?: never;
            };
            /** @description Поля для обновления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["transcript.UpdateSegmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["transcript.Segment"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить сегмент */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                    /** @description ID сегмента */
                    segmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/push/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить push-уведомление */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные уведомления */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["push.SendRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей (модератор+) */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["user.User"][];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить роль пользователя (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Новая роль */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.UpdateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["user.User"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить статус пользователя (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Новый статус */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.UpdateStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["user.User"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пометку по ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["annotation.Annotation"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Редактировать пометку */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Обновлённые данные */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["annotation.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["annotation.Annotation"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить свою пометку */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пометки */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["user.RegisterRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: {
                                token?: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["user.RegisterRequest"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["user.User"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Редактировать комментарий */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Новый текст */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["comment.UpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["comment.Comment"];
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Удалить свой комментарий */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Поставить реакцию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Реакция */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["comment.AddReactionRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Убрать реакцию */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID комментария */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список лекций */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                    /** @description Поиск по названию/описанию */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["lecture.Lecture"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить лекцию */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["lecture.Lecture"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пометок к лекции */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                    /** @description Фильтр по сегменту */
                    segment_id?: number;
                };
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["annotation.Annotation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Создать пометку */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Пометка */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["annotation.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["annotation.Annotation"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список комментариев к лекции */
        get: {
            parameters: {
                query?: {
                    /** @description Смещение */
                    offset?: number;
                    /** @description Записей на странице */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["comment.Comment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Создать комментарий */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Комментарий */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["comment.CreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["comment.Comment"];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список файлов лекции */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["lecturefile.LectureFile"][];
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lectures/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить транскрипт лекции */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID лекции */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["transcript.Transcript"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь и его права
         * @description Возвращает профиль авторизованного юзера + плоский список его
         *     capabilities — единственный авторитативный источник прав для
         *     клиента. Клиент НЕ должен выводить права из роли локально.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: components["schemas"]["user.MeResponse"];
                        };
                    };
                };
                /** @description no token / invalid / expired */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description account is banned */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description user from token no longer exists */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подписаться на push-уведомления */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Данные подписки */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["push.SubscribeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        /** Отписаться от push-уведомлений */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Endpoint подписки */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["push.UnsubscribeRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/vapid-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить VAPID public key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.Response"] & {
                            data?: {
                                publicKey?: string;
                            };
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Глобальный поиск */
        get: {
            parameters: {
                query: {
                    /** @description Поисковый запрос */
                    q: string;
                    /** @description Лимит результатов */
                    limit?: number;
                    /** @description Смещение */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ListResponse"] & {
                            data?: components["schemas"]["search.LectureHit"][];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httputil.ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "annotation.Annotation": {
            author?: components["schemas"]["annotation.Author"];
            body: string;
            comment_count?: number;
            created_at: string;
            id: string;
            is_anonymous?: boolean;
            is_edited?: boolean;
            is_private?: boolean;
            lecture_id: string;
            /** @description Populated by service */
            segment_ids?: number[];
            status: components["schemas"]["moderation.ModerationStatus"];
            updated_at: string;
            user_id?: string;
        };
        "annotation.Author": {
            username?: string;
        };
        "annotation.CreateRequest": {
            body: string;
            is_anonymous?: boolean;
            is_private?: boolean;
            lecture_id?: string;
            segment_ids: number[];
        };
        "annotation.UpdateRequest": {
            body: string;
            segment_ids: number[];
        };
        "audit.Record": {
            action?: string;
            actor_user_id?: string;
            actor_username?: string;
            created_at?: string;
            details?: {
                [key: string]: unknown;
            };
            id?: string;
            request_id?: string;
            target_id?: string;
            target_type?: string;
        };
        "comment.AddReactionRequest": {
            /** @enum {unknown} */
            reaction: "like";
        };
        "comment.Author": {
            username?: string;
        };
        "comment.Comment": {
            annotation_id?: string;
            /** @description Populated by service */
            author?: components["schemas"]["comment.Author"];
            body: string;
            created_at: string;
            id: string;
            is_anonymous?: boolean;
            is_edited?: boolean;
            lecture_id: string;
            my_reaction?: components["schemas"]["comment.ReactionType"];
            parent_id?: string;
            reactions?: components["schemas"]["comment.ReactionSummary"];
            replies?: components["schemas"]["comment.Comment"][];
            status: components["schemas"]["moderation.ModerationStatus"];
            updated_at: string;
            user_id?: string;
        };
        "comment.CreateRequest": {
            annotation_id?: string;
            body: string;
            is_anonymous?: boolean;
            lecture_id?: string;
            parent_id?: string;
        };
        "comment.ReactionSummary": {
            like?: number;
        };
        /** @enum {string} */
        "comment.ReactionType": "like";
        "comment.UpdateRequest": {
            body: string;
        };
        "httputil.ErrorResponse": {
            code?: string;
            error?: string;
        };
        "httputil.ListResponse": {
            data?: unknown;
            pagination?: components["schemas"]["httputil.Pagination"];
        };
        "httputil.Pagination": {
            limit?: number;
            offset?: number;
            total?: number;
        };
        "httputil.Response": {
            data?: unknown;
        };
        "httputil.ValidationErrorResponse": {
            code?: string;
            error?: string;
            fields?: {
                [key: string]: string;
            };
        };
        "lecture.CreateRequest": {
            date: string;
            description?: string;
            title: string;
        };
        "lecture.Lecture": {
            created_at: string;
            date: string;
            description: string;
            id: string;
            title: string;
            updated_at: string;
        };
        "lecture.UpdateRequest": {
            date?: string;
            description?: string;
            title?: string;
        };
        /** @enum {string} */
        "lecturefile.FileType": "video" | "notes" | "image";
        "lecturefile.LectureFile": {
            created_at: string;
            filename: string;
            id: string;
            lecture_id: string;
            sort_order?: number;
            type: components["schemas"]["lecturefile.FileType"];
            url?: string;
        };
        /** @enum {string} */
        "moderation.ModerationStatus": "published" | "hidden" | "pending";
        "moderation.UpdateStatusRequest": {
            /** @enum {unknown} */
            status: "published" | "hidden" | "pending";
        };
        "push.SendRequest": {
            body?: string;
            title: string;
            url?: string;
        };
        "push.SubscribeKeys": {
            auth: string;
            p256dh: string;
        };
        "push.SubscribeRequest": {
            endpoint: string;
            keys: components["schemas"]["push.SubscribeKeys"];
        };
        "push.UnsubscribeRequest": {
            endpoint: string;
        };
        /** @enum {string} */
        "rbac.Capability": "lecture.create" | "lecture.update" | "lecture.delete" | "lecture.upload_files" | "comment.moderate" | "comment.delete_any" | "annotation.moderate" | "annotation.delete_any" | "transcript.edit" | "user.list" | "user.moderate" | "push.send" | "admin.access";
        /** @enum {string} */
        "rbac.Role": "user" | "admin";
        /** @enum {string} */
        "rbac.Status": "active" | "suspended" | "banned";
        "search.LectureHit": {
            date: string;
            lecture_id: string;
            matches?: components["schemas"]["search.Match"][];
            title: string;
        };
        "search.Match": {
            segment_id?: string;
            source: string;
            text: string;
        };
        "transcript.CreateSegmentRequest": {
            end?: number;
            position?: number;
            speaker: string;
            start?: number;
            text: string;
        };
        "transcript.Segment": {
            end?: number;
            id: string;
            position?: number;
            speaker: string;
            start?: number;
            text: string;
        };
        "transcript.Transcript": {
            created_at: string;
            id: string;
            lecture_id: string;
            segments?: components["schemas"]["transcript.Segment"][];
            updated_at: string;
        };
        "transcript.UpdateSegmentRequest": {
            end?: number;
            position?: number;
            speaker?: string;
            start?: number;
            text?: string;
        };
        "transcript.upsertRequest": {
            segments?: components["schemas"]["transcript.Segment"][];
        };
        "user.MeResponse": {
            capabilities?: components["schemas"]["rbac.Capability"][];
            id?: string;
            role?: components["schemas"]["rbac.Role"];
            status?: components["schemas"]["rbac.Status"];
            username?: string;
        };
        "user.RegisterRequest": {
            password: string;
            username: string;
        };
        "user.UpdateRoleRequest": {
            /** @enum {unknown} */
            role: "user" | "admin";
        };
        "user.UpdateStatusRequest": {
            /** @enum {unknown} */
            status: "active" | "suspended" | "banned";
        };
        "user.User": {
            created_at: string;
            id: string;
            role: components["schemas"]["rbac.Role"];
            status: components["schemas"]["rbac.Status"];
            updated_at: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Новый статус */
        "moderation.UpdateStatusRequest": {
            content: {
                "application/json": components["schemas"]["moderation.UpdateStatusRequest"];
            };
        };
        /** @description Username и пароль */
        "user.RegisterRequest": {
            content: {
                "application/json": components["schemas"]["user.RegisterRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
