import { Author } from "next/dist/lib/metadata/types/metadata-types";

type Section =
  | "Интро"
  | "Экспериментальная наука"
  | "Античная этика"
  | "Новоевропейская теория познания";

export type PageData = {
  /** заголовок лекции */
  title: string;
  /** номер лекции */
  order: number;
  /** url сегмент в url страницы после /lectures */
  slug: string;
  /** путь до docx файла лекции */
  docxUrl: string;
  /** путь до обдожки лекции */
  cover?: string;

  /** упомянутые в лекции личности */
  mentions: string[];
  /** раздел лекций */
  section: Section;

  meta?: {
    description?: string;
    creator?: null | string | undefined;
    category?: null | string | undefined;
    keywords?: null | string | Array<string> | undefined;
    authors?: null | Author | Array<Author> | undefined;
  };
};

export const structure: PageData[] = [
  {
    title: "Не ассорти",
    order: 1,
    slug: "lesson-1",
    docxUrl: "/lesson-1.docx",
    cover: "/logo.png",
    section: "Интро",
    mentions: ["Пифагор"],
    meta: {},
  },
  {
    title: "Презумпция ненаивности",
    order: 2,
    slug: "lesson-2",
    docxUrl: "/lesson-2.docx",
    cover: "/lesson-previews/lesson-2-preview.jpeg",
    section: "Интро",
    mentions: ["Пифагор"],
    meta: {},
  },
  {
    title: "Отцы философии",
    order: 3,
    slug: "lesson-3",
    docxUrl: "/lesson-3.docx",
    cover: "/lesson-previews/lesson-3-preview.jpeg",
    section: "Интро",
    mentions: ["Парменид", "Гераклит"],
    meta: {},
  },
  {
    title: "Неразрешимые противоречия",
    order: 4,
    slug: "lesson-4",
    docxUrl: "/lesson-4.docx",
    cover: "/lesson-previews/lesson-4-preview.jpeg",
    section: "Интро",
    mentions: ["Зенон", "Парменид", "Гераклит"],
    meta: {},
  },
  {
    title: "Предельное основание",
    order: 5,
    slug: "lesson-5",
    docxUrl: "/lesson-5.docx",
    cover: "/lesson-previews/lesson-5-preview.jpeg",
    section: "Интро",
    mentions: ["Сократ"],
    meta: {},
  },
  {
    title: "От суда к сотворению",
    order: 6,
    slug: "lesson-6",
    docxUrl: "/lesson-6.docx",
    cover: "/lesson-previews/lesson-6-preview.jpeg",
    section: "Интро",
    mentions: ["Фома Аквинский"],
    meta: {},
  },
  {
    title: "Свобода воли, грех и спасение",
    order: 7,
    slug: "lesson-7",
    docxUrl: "/lesson-7.docx",
    cover: "/lesson-previews/lesson-7-preview.jpeg",
    section: "Интро",
    mentions: ["Августин Аврелий", "Пелагий", "Мартин Лютер"],
    meta: {},
  },
  {
    title: "Gracia",
    order: 8,
    slug: "lesson-8",
    docxUrl: "/lesson-8.docx",
    cover: "/lesson-previews/lesson-8-preview.jpeg",
    section: "Интро",
    mentions: ["Августин Аврелий", "Пелагий", "Мартин Лютер", "Жан Кальвин"],
    meta: {},
  },
  {
    title: "Лоскутное одеяло",
    order: 9,
    slug: "lesson-9",
    docxUrl: "/lesson-9.docx",
    cover: "/lesson-previews/lesson-9-preview.jpeg",
    section: "Интро",
    mentions: ["Рене Декарт", "Галилей"],
    meta: {},
  },
  {
    title: "Точка опоры",
    order: 10,
    slug: "lesson-10",
    docxUrl: "/lesson-10.docx",
    cover: "/lesson-previews/lesson-10-preview.jpeg",
    section: "Интро",
    mentions: ["Рене Декарт"],
    meta: {},
  },
  {
    title: "Бог из логики",
    order: 11,
    slug: "lesson-11",
    docxUrl: "/lesson-11.docx",
    cover: "/lesson-previews/lesson-11-preview.jpeg",
    section: "Интро",
    mentions: ["Рене Декарт"],
    meta: {},
  },
  {
    title: "Очень холодная ночь",
    order: 12,
    slug: "lesson-12",
    docxUrl: "/lesson-12.docx",
    cover: "/lesson-previews/lesson-12-preview.jpeg",
    section: "Интро",
    mentions: ["Рене Декарт", "Гоббс"],
    meta: {},
  },
  {
    title: "Непознаваемый стул",
    order: 13,
    slug: "lesson-13",
    docxUrl: "/lesson-13.docx",
    cover: "/lesson-previews/lesson-13-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Платон"],
    meta: {},
  },
  {
    title: "Слепой бог",
    order: 14,
    slug: "lesson-14",
    docxUrl: "/lesson-14.docx",
    cover: "/lesson-previews/lesson-14-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Аристотель"],
    meta: {},
  },
  {
    title: "Схоластика",
    order: 15,
    slug: "lesson-15",
    docxUrl: "/lesson-15.docx",
    cover: "/lesson-previews/lesson-15-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Фома Аквинский", "Уильям Оккам"],
    meta: {},
  },
  {
    title: "Порывая со здравым смыслом",
    order: 16,
    slug: "lesson-16",
    docxUrl: "/lesson-16.docx",
    cover: "/lesson-previews/lesson-16-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: [
      "Галилей",
      "Коперник",
      //  "Френсис Бэкон"
    ],
    meta: {},
  },
  {
    title: "Единственный в своём роде",
    order: 17,
    slug: "lesson-17",
    docxUrl: "/lesson-17.docx",
    cover: "/lesson-previews/lesson-17-preview.jpeg",
    section: "Античная этика",
    mentions: ["Диоген Синопский"],
    meta: {},
  },
  {
    title: "Одно мгновение",
    order: 18,
    slug: "lesson-18",
    docxUrl: "/lesson-18.docx",
    cover: "/lesson-previews/lesson-18-preview.jpeg",
    section: "Античная этика",
    mentions: ["Хрисипп", "Марк Аврелий"],
    meta: {},
  },
  {
    title: "Сходство с пылью",
    order: 19,
    slug: "lesson-19",
    docxUrl: "/lesson-19.docx",
    cover: "/lesson-previews/lesson-19-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Сорта удовольствий",
    order: 20,
    slug: "lesson-20",
    docxUrl: "/lesson-20.docx",
    cover: "/lesson-previews/lesson-20-preview.jpeg",
    section: "Античная этика",
    mentions: ["Эпикур"],
    meta: {},
  },
  {
    title: "Второй шанс",
    order: 21,
    slug: "lesson-21",
    docxUrl: "/lesson-21.docx",
    cover: "/lesson-previews/lesson-21-preview.jpeg",
    section: "Античная этика",
    mentions: ["Эпикур"],
    meta: {},
  },
  {
    title: "Четыре варианта смерти",
    order: 22,
    slug: "lesson-22",
    docxUrl: "/lesson-22.docx",
    cover: "/lesson-previews/lesson-22-preview.jpeg",
    section: "Античная этика",
    mentions: ["Эпикур"],
    meta: {},
  },
  {
    title: "Секст и пустота",
    order: 23,
    slug: "lesson-23",
    docxUrl: "/lesson-23.docx",
    cover: "/lesson-previews/lesson-23-preview.jpeg",
    section: "Античная этика",
    mentions: [
      "Секст Эмпирик",
      // "Мелани Кляйн"
    ],
    meta: {},
  },
  {
    title: "Что со мной не так",
    order: 24,
    slug: "lesson-24",
    docxUrl: "/lesson-24.docx",
    cover: "/lesson-previews/lesson-24-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Бесконечное падение",
    order: 25,
    slug: "lesson-25",
    docxUrl: "/lesson-25.docx",
    cover: "/lesson-previews/lesson-25-preview.jpeg",
    section: "Античная этика",
    mentions: ["Иисус Христос", "Апостол Павел"],
    meta: {},
  },
  {
    title: "Фокусы со временем",
    order: 26,
    slug: "lesson-26",
    docxUrl: "/lesson-26.docx",
    cover: "/lesson-previews/lesson-26-preview.jpeg",
    section: "Античная этика",
    mentions: [
      "Апостол Павел",
      // "Джордж Агамбен"
    ],
    meta: {},
  },
  {
    title: "Потеряли счёт",
    order: 27,
    slug: "lesson-27",
    docxUrl: "/lesson-27.docx",
    cover: "/lesson-previews/lesson-27-preview.jpeg",
    section: "Античная этика",
    mentions: [
      "Савеллий",
      "Тертуллиан",
      "Арий",
      "Евномий",
      "Василий Великий",
      "Григорий Богослов",
      "Григорий Нисский",
      // "Жак Деррида",
    ],
    meta: {},
  },
  {
    title: "И от сына тоже",
    order: 28,
    slug: "lesson-28",
    docxUrl: "/lesson-28.docx",
    cover: "/lesson-previews/lesson-28-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Si fallor, sum",
    order: 29,
    slug: "lesson-29",
    docxUrl: "/lesson-29.docx",
    cover: "/lesson-previews/lesson-29-preview.jpeg",
    section: "Античная этика",
    mentions: ["Августин Аврелий", "Рене Декарт"],
    meta: {},
  },
  {
    title: "Сколько субстанций?",
    order: 30,
    slug: "lesson-30",
    docxUrl: "/lesson-30.docx",
    cover: "/lesson-previews/lesson-30-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Локк", "Беркли"],
    meta: {},
  },
  {
    title: "Быть",
    order: 31,
    slug: "lesson-31",
    docxUrl: "/lesson-31.docx",
    cover: "/lesson-previews/lesson-31-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Беркли", "Молинью"],
    meta: {},
  },
  {
    title: "Никаких больше субстанций",
    order: 32,
    slug: "lesson-32",
    docxUrl: "/lesson-32.docx",
    cover: "/lesson-previews/lesson-32-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Юм"],
    meta: {},
  },
  {
    title: "Случайность",
    order: 33,
    slug: "lesson-33",
    docxUrl: "/lesson-33.docx",
    cover: "/lesson-previews/lesson-33-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Юм"],
    meta: {},
  },
  {
    title: "??",
    order: 34,
    slug: "lesson-34",
    docxUrl: "/lesson-34.docx",
    cover: "/lesson-previews/lesson-34-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Юм"],
    meta: {},
  },
];
