import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { TOKENS } from "../src/styles/tokens/index.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { colorLayers, scales } = TOKENS;
const colorVars = (layer) => Object.entries(layer).map(([k, v]) => `  --${k}: ${v};`).join("\n");

// Не-цветовые шкалы → в @theme (Tailwind строит из них утилиты text-*/rounded-*/...).
const themeScales = () => {
  const L = [];
  for (const [s, { size, line }] of Object.entries(scales.TYPE_SCALE)) {
    L.push(`  --text-${s}: ${size};`, `  --text-${s}--line-height: ${line};`);
  }
  for (const [k, v] of Object.entries(scales.RADIUS)) L.push(`  --radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(scales.SHADOW)) L.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(scales.DURATION)) L.push(`  --duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(scales.Z)) L.push(`  --z-${k}: ${v};`);
  // px-брейкпоинты + header
  L.push(`  --breakpoint-sm: 640px;`, `  --breakpoint-md: 768px;`, `  --breakpoint-lg: 1024px;`,
         `  --breakpoint-xl: 1280px;`, `  --breakpoint-2xl: 1536px;`, `  --spacing-header: 50px;`);
  return L.join("\n");
};

// Цвет + шрифт → @theme inline (utility ссылается на рантайм-var, переключаемую через data-*).
const themeInline = () => {
  const names = Object.keys(colorLayers["light-normal"]);
  return `@theme inline {\n${names.map((n) => `  --color-${n}: var(--${n});`).join("\n")}\n  --font-ui: var(--app-font);\n}`;
};

const densityVars = (name) => {
  const d = scales.DENSITY[name];
  return [
    `  --size-control-h-sm: ${d.controlH.sm};`, `  --size-control-h-md: ${d.controlH.md};`,
    `  --size-control-h-lg: ${d.controlH.lg};`, `  --space-control-pad-x: ${d.padX};`,
    `  --space-control-pad-y: ${d.padY};`, `  --space-stack: ${d.stack};`,
  ].join("\n");
};

const css = `/* AUTO-GENERATED by scripts/generate-tokens.mjs — DO NOT EDIT.
   Source: src/styles/tokens/*. Run \`pnpm generate:tokens\`. */

@theme {
${themeScales()}
}

${themeInline()}

:root {
${colorVars(colorLayers["light-normal"])}
${densityVars("comfortable")}
  --app-font: ${scales.FONT_STACKS.sans};
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars(colorLayers["dark-normal"]).replace(/^/gm, "  ")}
  }
}

[data-theme="dark"] {
${colorVars(colorLayers["dark-normal"])}
}

[data-theme="light"] {
${colorVars(colorLayers["light-normal"])}
}

/* high contrast (explicit data-contrast="high"), resolved per theme */
[data-theme="light"][data-contrast="high"] {
${colorVars(colorLayers["light-high"])}
}
[data-theme="dark"][data-contrast="high"] {
${colorVars(colorLayers["dark-high"])}
}
@media (prefers-color-scheme: light) {
  :root:not([data-theme])[data-contrast="high"] {
${colorVars(colorLayers["light-high"]).replace(/^/gm, "  ")}
  }
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme])[data-contrast="high"] {
${colorVars(colorLayers["dark-high"]).replace(/^/gm, "  ")}
  }
}

/* OS prefers-contrast: more — auto-boost for users with NO explicit data-contrast, per resolved theme */
@media (prefers-contrast: more) {
  :root:not([data-contrast]):not([data-theme="dark"]) {
${colorVars(colorLayers["light-high"]).replace(/^/gm, "  ")}
  }
}
@media (prefers-contrast: more) and (prefers-color-scheme: dark) {
  :root:not([data-contrast]):not([data-theme="light"]) {
${colorVars(colorLayers["dark-high"]).replace(/^/gm, "  ")}
  }
}

[data-density="compact"] {
${densityVars("compact")}
}

[data-font="legible"] { --app-font: ${scales.FONT_STACKS.legible}; }
[data-font="serif"]   { --app-font: ${scales.FONT_STACKS.serif}; }
`;

writeFileSync(resolve(root, "src/styles/tokens.generated.css"), css);
console.log("[generate-tokens] wrote src/styles/tokens.generated.css");
