import { Author } from "next/dist/lib/metadata/types/metadata-types";

type Section =
  | "Интро"
  | "Экспериментальная наука"
  | "Античная этика"
  | "Новоевропейская теория познания";

export type PageData = {
  /** заголовок лекции */
  title: string;
  /** номер лекции */
  order: number;
  /** url сегмент в url страницы после /lectures */
  slug: string;
  /** путь до docx файла лекции */
  docxUrl: string;
  /** путь до обдожки лекции */
  cover?: string;

  /** упомянутые в лекции личности */
  mentions: string[];
  /** раздел лекций */
  section: Section;

  meta?: {
    description?: string;
    creator?: null | string | undefined;
    category?: null | string | undefined;
    keywords?: null | string | Array<string> | undefined;
    authors?: null | Author | Array<Author> | undefined;
  };
};

export const structure: PageData[] = [
  {
    title: "Введение",
    order: 1,
    slug: "lesson-1",
    docxUrl: "/lesson-1.docx",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Презумпция ненаивности",
    order: 2,
    slug: "lesson-2",
    docxUrl: "/lesson-2.docx",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Отцы философии",
    order: 3,
    slug: "lesson-3",
    docxUrl: "/lesson-3.docx",
    cover: "/lesson-previews/lesson-3-preview.jpeg",
    section: "Интро",
    mentions: ["Парменид", "Гераклит"],
    meta: {},
  },
  {
    title: "Зенон и апории",
    order: 4,
    slug: "lesson-4",
    docxUrl: "/lesson-4.docx",
    section: "Интро",
    mentions: ["Зенон"],
    meta: {},
  },
  {
    title: "Суд Сократа",
    order: 5,
    slug: "lesson-5",
    docxUrl: "/lesson-5.docx",
    cover: "/lesson-previews/lesson-5-preview.jpeg",
    section: "Интро",
    mentions: ["Сократ"],
    meta: {},
  },
  {
    title: "Введение в монотеизм",
    order: 6,
    slug: "lesson-6",
    docxUrl: "/lesson-6.docx",
    cover: "/lesson-previews/lesson-6-preview.jpeg",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Свобода воли, грех и спасение",
    order: 7,
    slug: "lesson-7",
    docxUrl: "/lesson-7.docx",
    cover: "/lesson-previews/lesson-7-preview.jpeg",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Gracia",
    order: 8,
    slug: "lesson-8",
    docxUrl: "/lesson-8.docx",
    cover: "/lesson-previews/lesson-8-preview.jpeg",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Введение в модерн",
    order: 9,
    slug: "lesson-9",
    docxUrl: "/lesson-9.docx",
    cover: "/lesson-previews/lesson-9-preview.jpeg",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Точка опоры",
    order: 10,
    slug: "lesson-10",
    docxUrl: "/lesson-10.docx",
    cover: "/lesson-previews/lesson-10-preview.jpeg",
    section: "Интро",
    mentions: [],
    meta: {},
  },
  {
    title: "Бог из логики",
    order: 11,
    slug: "lesson-11",
    docxUrl: "/lesson-11.docx",
    cover: "/lesson-previews/lesson-11-preview.jpeg",
    section: "Интро",
    mentions: ["Декарт"],
    meta: {},
  },
  {
    title: "Очень короткое одеяло",
    order: 12,
    slug: "lesson-12",
    docxUrl: "/lesson-12.docx",
    cover: "/lesson-previews/lesson-12-preview.jpeg",
    section: "Интро",
    mentions: ["Декарт", "Гоббс"],
    meta: {},
  },
  {
    title: "Исток экспериментальной науки",
    order: 13,
    slug: "lesson-13",
    docxUrl: "/lesson-13.docx",
    cover: "/lesson-previews/lesson-13-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Платон"],
    meta: {},
  },
  {
    title: "Аристотель",
    order: 14,
    slug: "lesson-14",
    docxUrl: "/lesson-14.docx",
    cover: "/lesson-previews/lesson-14-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Аристотель"],
    meta: {},
  },
  {
    title: "Схоластика",
    order: 15,
    slug: "lesson-15",
    docxUrl: "/lesson-15.docx",
    cover: "/lesson-previews/lesson-15-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: [],
    meta: {},
  },
  {
    title: "Галилей",
    order: 16,
    slug: "lesson-16",
    docxUrl: "/lesson-16.docx",
    cover: "/lesson-previews/lesson-16-preview.jpeg",
    section: "Экспериментальная наука",
    mentions: ["Галилей"],
    meta: {},
  },
  {
    title: "Введение в этику",
    order: 17,
    slug: "lesson-17",
    docxUrl: "/lesson-17.docx",
    cover: "/lesson-previews/lesson-17-preview.jpeg",
    section: "Античная этика",
    mentions: ["Диоген Синопский"],
    meta: {},
  },
  {
    title: "Стоицизм",
    order: 18,
    slug: "lesson-18",
    docxUrl: "/lesson-18.docx",
    cover: "/lesson-previews/lesson-18-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Физика стоиков",
    order: 19,
    slug: "lesson-19",
    docxUrl: "/lesson-19.docx",
    cover: "/lesson-previews/lesson-19-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Эпикурейство",
    order: 20,
    slug: "lesson-20",
    docxUrl: "/lesson-20.docx",
    cover: "/lesson-previews/lesson-20-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Физика Эпикура",
    order: 21,
    slug: "lesson-21",
    docxUrl: "/lesson-21.docx",
    cover: "/lesson-previews/lesson-21-preview.jpeg",
    section: "Античная этика",
    mentions: ["Эпикур"],
    meta: {},
  },
  {
    title: "Проблемы эпикурейцев",
    order: 22,
    slug: "lesson-22",
    docxUrl: "/lesson-22.docx",
    cover: "/lesson-previews/lesson-22-preview.jpeg",
    section: "Античная этика",
    mentions: ["Эпикур"],
    meta: {},
  },
  {
    title: "Пустота у стоиков. Скептицизм",
    order: 23,
    slug: "lesson-23",
    docxUrl: "/lesson-23.docx",
    cover: "/lesson-previews/lesson-23-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "От скептицизма к христианству",
    order: 24,
    slug: "lesson-24",
    docxUrl: "/lesson-24.docx",
    cover: "/lesson-previews/lesson-24-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Этика Христа",
    order: 25,
    slug: "lesson-25",
    docxUrl: "/lesson-25.docx",
    cover: "/lesson-previews/lesson-25-preview.jpeg",
    section: "Античная этика",
    mentions: ["Иисус Христос"],
    meta: {},
  },
  {
    title: "Возникновение христианской этики",
    order: 26,
    slug: "lesson-26",
    docxUrl: "/lesson-26.docx",
    cover: "/lesson-previews/lesson-26-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Онтология христианства",
    order: 27,
    slug: "lesson-27",
    docxUrl: "/lesson-27.docx",
    cover: "/lesson-previews/lesson-27-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Онтология христианства. Часть 2",
    order: 28,
    slug: "lesson-28",
    docxUrl: "/lesson-28.docx",
    cover: "/lesson-previews/lesson-28-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "От христианства к Новоевропейской теории познания",
    order: 29,
    slug: "lesson-29",
    docxUrl: "/lesson-29.docx",
    cover: "/lesson-previews/lesson-29-preview.jpeg",
    section: "Античная этика",
    mentions: [],
    meta: {},
  },
  {
    title: "Теория познания. Новое время",
    order: 30,
    slug: "lesson-30",
    docxUrl: "/lesson-30.docx",
    cover: "/lesson-previews/lesson-30-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Локк"],
    meta: {},
  },
  {
    title: "Больше о Беркли и абстракциях",
    order: 31,
    slug: "lesson-31",
    docxUrl: "/lesson-31.docx",
    cover: "/lesson-previews/lesson-31-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Беркли"],
    meta: {},
  },
  {
    title: "Дэвид Юм",
    order: 32,
    slug: "lesson-32",
    docxUrl: "/lesson-32.docx",
    cover: "/lesson-previews/lesson-32-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Юм"],
    meta: {},
  },
  {
    title: "Дэвид Юм. Часть 2",
    order: 33,
    slug: "lesson-33",
    docxUrl: "/lesson-33.docx",
    cover: "/lesson-previews/lesson-33-preview.jpeg",
    section: "Новоевропейская теория познания",
    mentions: ["Юм"],
    meta: {},
  },
];
